repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0  # check for latest version
    hooks:
      - id: ruff
        # No --fix so you see the same errors as CI
      - id: ruff-format  # if you also want formatting

