#!/usr/bin/env python3
"""
Generate an index of all notable entries in the data/notables directory.

This script scans all YAML files in births/ and events/ subdirectories,
extracts the names and categories, and generates a sorted index file.

Usage:
    python data/notables/generate_index.py

Output:
    data/notables/INDEX.md - Markdown file listing all notables by category
"""

from pathlib import Path

import click
import yaml


def load_notables_from_file(filepath: Path) -> list[dict]:
    """Load notable entries from a YAML file."""
    with open(filepath) as f:
        data = yaml.safe_load(f)
    return data if data else []


def format_birth_datetime(entry: dict) -> str:
    """Render an entry's birth date + clock time as ``YYYY-MM-DD HH:MM``.

    Missing month/day fall back to ``??``; missing hour/minute to ``00``.
    """
    year = entry.get("year")
    month = entry.get("month")
    day = entry.get("day")
    hour = entry.get("hour", 0) or 0
    minute = entry.get("minute", 0) or 0

    year_str = f"{year:04d}" if isinstance(year, int) else str(year or "????")
    month_str = f"{month:02d}" if isinstance(month, int) else "??"
    day_str = f"{day:02d}" if isinstance(day, int) else "??"
    return f"{year_str}-{month_str}-{day_str} {hour:02d}:{minute:02d}"


def is_noon_placeholder(entry: dict) -> bool:
    """True when the stored time is the 12:00 unknown-time default."""
    return (entry.get("hour"), entry.get("minute", 0)) == (12, 0)


def resolve_time_reliability(entry: dict) -> bool | None:
    """Resolve an entry's time-reliability as a genuine tri-state.

    ``has_reliable_time`` is *not* present on every entry (it was retrofitted
    onto a curation subset), so its absence carries **no** information — it
    means "not yet assessed", not "unreliable". We therefore never default it:

    * **Explicit flag present** -> ``True`` / ``False`` (a deliberate curator
      override, e.g. Golda Meir is AA by *date* but a 12:00 noon default ->
      ``False``; the Dalai Lama's time is contested -> ``False``).
    * **Flag absent** -> ``None`` (unknown). The rating and the noon-placeholder
      fact are surfaced alongside so a consumer can triage: AstroDatabank AA/A
      are *time* ratings (AA = birth certificate, A = family/memory), so an
      un-flagged AA/A entry with a real (non-noon) time is *probably* usable,
      but that judgement is left explicit rather than fabricated here.
    """
    if "has_reliable_time" in entry:
        return bool(entry["has_reliable_time"])
    return None


def main():
    # Get the directory where this script lives
    script_dir = Path(__file__).parent

    # Collect all notables
    births = {}  # category -> list of names
    events = []

    # Scan births directory
    births_dir = script_dir / "births"
    if births_dir.exists():
        for yaml_file in sorted(births_dir.glob("*.yaml")):
            entries = load_notables_from_file(yaml_file)
            for entry in entries:
                name = entry.get("name", "Unknown")
                category = entry.get("category", "uncategorized")
                subcats = entry.get("subcategories", [])
                year = entry.get("year", "?")
                notable_for = entry.get("notable_for", "")

                if category not in births:
                    births[category] = []
                births[category].append(
                    {
                        "name": name,
                        "year": year,
                        "subcategories": subcats,
                        "notable_for": notable_for,
                        "source_file": yaml_file.name,
                        "birth_datetime": format_birth_datetime(entry),
                        "location_name": entry.get("location_name", "unknown"),
                        "timezone": entry.get("timezone", ""),
                        "rating": entry.get("data_quality") or "unrated",
                        "time_reliable": resolve_time_reliability(entry),
                        "noon_placeholder": is_noon_placeholder(entry),
                    }
                )

    # Scan events directory
    events_dir = script_dir / "events"
    if events_dir.exists():
        for yaml_file in sorted(events_dir.glob("*.yaml")):
            entries = load_notables_from_file(yaml_file)
            for entry in entries:
                name = entry.get("name", "Unknown")
                year = entry.get("year", "?")
                notable_for = entry.get("notable_for", "")

                events.append(
                    {
                        "name": name,
                        "year": year,
                        "notable_for": notable_for,
                        "source_file": yaml_file.name,
                    }
                )

    # Generate the index markdown
    lines = [
        "# Stellium Notables Index",
        "",
        "This file is auto-generated by `generate_index.py`.",
        "",
        f"**Total entries:** {sum(len(v) for v in births.values()) + len(events)}",
        "",
        "Each birth entry lists, on its second line: `birth date + local clock "
        "time · place [IANA timezone] · rating · time-reliability`. The **rating** "
        "is the Rodden data quality (`AA`/`A`/`B`/`C`/`DD`/`X`/`unrated`). "
        "**Time reliability** is a tri-state curation flag (`has_reliable_time`):",
        "",
        "- *time reliable* — curator-confirmed the clock time is trustworthy.",
        "- *time NOT reliable* — curator flagged the time as unusable (disputed, "
        "rounded, or a `12:00` noon placeholder). Never treat as ground truth.",
        "- *time reliability unverified* — **not yet assessed** (the flag was "
        "retrofitted onto a subset; absence is not a negative signal). Triage by "
        "the rating + noon flag: AstroDatabank `AA`/`A` are *time* ratings "
        "(AA = birth certificate, A = family/memory), so an *unverified* `AA`/`A` "
        "entry on a real (non-noon) time is very likely usable ground truth.",
        "",
        "For the rectification corpus, use entries that are `AA`/`A` **and** "
        "either *time reliable* or *unverified with a real (non-noon) time*; "
        "exclude anything *NOT reliable* or sitting on a noon placeholder.",
        "",
    ]

    # Births section
    lines.append("## Births")
    lines.append("")

    for category in sorted(births.keys()):
        entries = births[category]
        lines.append(f"### {category.title()} ({len(entries)})")
        lines.append("")

        # Sort by name
        for entry in sorted(entries, key=lambda x: x["name"]):
            subcats = (
                ", ".join(entry["subcategories"]) if entry["subcategories"] else ""
            )
            subcat_str = f" ({subcats})" if subcats else ""

            loc = entry["location_name"]
            tz = f" [{entry['timezone']}]" if entry["timezone"] else ""
            reliable = entry["time_reliable"]
            if reliable is True:
                time_flag = "time reliable"
            elif reliable is False:
                time_flag = "time NOT reliable"
            else:
                time_flag = "time reliability unverified"
            if entry["noon_placeholder"]:
                time_flag += " (noon placeholder)"
            lines.append(f"- **{entry['name']}** ({entry['year']}){subcat_str}")
            lines.append(
                f"  - {entry['birth_datetime']} · {loc}{tz} · "
                f"rating {entry['rating']} · {time_flag}"
            )

        lines.append("")

    # Events section
    if events:
        lines.append("## Events")
        lines.append("")

        for entry in sorted(events, key=lambda x: x["name"]):
            lines.append(f"- **{entry['name']}** ({entry['year']})")

        lines.append("")

    # Write the index file
    index_path = script_dir / "INDEX.md"
    with open(index_path, "w") as f:
        f.write("\n".join(lines))

    click.echo(f"Generated {index_path}")
    click.echo(
        f"  Births: {sum(len(v) for v in births.values())} entries across {len(births)} categories"
    )
    click.echo(f"  Events: {len(events)} entries")


if __name__ == "__main__":
    main()
