#!/usr/bin/env python3
"""
Build the web fonts the documentation site serves.

    python scripts/build_web_fonts.py

The docs theme used to pull its four faces from the **Google Fonts CDN**. That
works, but it means every reader of our documentation makes a request to Google,
the site cannot be read offline or built into an air-gapped environment, and the
page flashes unstyled text while the CDN answers. So we serve them ourselves.

Sources live in `assets/fonts/` — the repository's font home, *not*
`src/stellium/data/fonts/`, which ships inside the wheel and is kept to what the
PDF renderer actually needs. Nothing here is packaged.

Output is **woff2**, which is what a browser wants: roughly a quarter the size of
the TTF, and universally supported for a decade. `docs/conf.py` adds the output
directory to `html_static_path`, so the files land in `_static/` and the theme's
`@font-face` rules point at them.

Requires fontTools + brotli (dev extras).
"""

from __future__ import annotations

from pathlib import Path

from fontTools.ttLib import TTFont

REPO = Path(__file__).resolve().parent.parent
ASSETS = REPO / "assets" / "fonts"
PACKAGE_FONTS = REPO / "src" / "stellium" / "data" / "fonts"
OUT = ASSETS / "web"

# (source file, output name, css family, weight, style)
FACES: list[tuple[Path, str, str, int, str]] = [
    # The wordmark. All-caps and heavy — used for nothing else.
    (
        ASSETS / "Cinzel_Decorative/CinzelDecorative-Bold.ttf",
        "CinzelDecorative-Bold",
        "Cinzel Decorative",
        700,
        "normal",
    ),
    # Display: headings.
    (
        PACKAGE_FONTS / "Spectral-Regular.ttf",
        "Spectral-Regular",
        "Spectral",
        400,
        "normal",
    ),
    (
        PACKAGE_FONTS / "Spectral-Medium.ttf",
        "Spectral-Medium",
        "Spectral",
        500,
        "normal",
    ),
    (PACKAGE_FONTS / "Spectral-Bold.ttf", "Spectral-Bold", "Spectral", 700, "normal"),
    (
        PACKAGE_FONTS / "Spectral-Italic.ttf",
        "Spectral-Italic",
        "Spectral",
        400,
        "italic",
    ),
    # UI and body.
    (
        ASSETS / "IBM_Plex_Sans/IBMPlexSans-Regular.ttf",
        "IBMPlexSans-Regular",
        "IBM Plex Sans",
        400,
        "normal",
    ),
    (
        ASSETS / "IBM_Plex_Sans/IBMPlexSans-Medium.ttf",
        "IBMPlexSans-Medium",
        "IBM Plex Sans",
        500,
        "normal",
    ),
    (
        ASSETS / "IBM_Plex_Sans/IBMPlexSans-SemiBold.ttf",
        "IBMPlexSans-SemiBold",
        "IBM Plex Sans",
        600,
        "normal",
    ),
    (
        ASSETS / "IBM_Plex_Sans/IBMPlexSans-Bold.ttf",
        "IBMPlexSans-Bold",
        "IBM Plex Sans",
        700,
        "normal",
    ),
    # Code, and every mono label in the design.
    (
        PACKAGE_FONTS / "IBMPlexMono-Regular.otf",
        "IBMPlexMono-Regular",
        "IBM Plex Mono",
        400,
        "normal",
    ),
    (
        PACKAGE_FONTS / "IBMPlexMono-Bold.otf",
        "IBMPlexMono-Bold",
        "IBM Plex Mono",
        700,
        "normal",
    ),
]


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)

    css: list[str] = [
        "/* Generated by scripts/build_web_fonts.py — do not edit by hand. */",
        "/* Self-hosted so the docs make no request to a font CDN, read offline, */",
        "/* and never flash unstyled text while a third party answers.          */",
        "",
    ]
    total = 0
    for source, stem, family, weight, style in FACES:
        if not source.exists():
            raise SystemExit(f"missing source font: {source}")

        font = TTFont(source)
        font.flavor = "woff2"
        target = OUT / f"{stem}.woff2"
        font.save(target)

        size = target.stat().st_size
        total += size
        print(f"  {stem:26} {source.suffix[1:]:3} -> woff2  {size / 1024:6.1f} KB")

        css.append(
            f"@font-face{{font-family:'{family}';font-style:{style};font-weight:{weight};"
            f"font-display:swap;src:url('{stem}.woff2') format('woff2');}}"
        )

    (OUT / "stellium-fonts.css").write_text("\n".join(css) + "\n")
    print(f"\n  {len(FACES)} faces, {total / 1024:.0f} KB total")
    print(f"  wrote {OUT.relative_to(REPO)}/stellium-fonts.css")


if __name__ == "__main__":
    main()
