import os
import sys

sys.path.insert(0, os.path.abspath("../src"))
# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

# Import version from package to avoid hardcoding
from stellium import __version__

project = "Stellium"
copyright = "2025, Kate Louie"
author = "Kate Louie"
release = __version__

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    "sphinx.ext.autodoc",  # Auto-generate docs from docstrings
    "sphinx.ext.napoleon",  # Support Google/NumPy docstrings
    "sphinx.ext.viewcode",  # Add links to source code
    "sphinx.ext.intersphinx",  # Link to other docs
    "sphinx_autodoc_typehints",  # Better type hints
    "myst_parser",  # MARKDOWN SUPPORT!
]

# MyST configuration
myst_enable_extensions = [
    "colon_fence",  # ::: fences
    "deflist",  # Definition lists
    "tasklist",  # Task lists
]

# Source file suffixes
source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store", "archive", "planning"]


# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = "stellium_theme"
html_theme_path = ["_themes"]

html_theme_options = {
    # These are declared in theme.conf and rendered into stellium.css_t, so they
    # genuinely drive the palette — they are not decoration.
    "accent": "#5b46b0",
    "accent_dark": "#9b8ae8",
    "gold": "#a9782a",
    "gold_dark": "#d9b46a",
    "github_url": "https://github.com/katelouie/stellium",
    "default_mode": "light",
    "show_version": True,
}

html_title = "Stellium"
html_short_title = "Stellium"

# The docs' web fonts are generated by scripts/build_web_fonts.py and live in
# assets/fonts/web/ — the repo's font home, NOT src/stellium/data/fonts/, which
# ships in the wheel. Adding the directory here copies the .woff2 into _static/,
# where the theme's @font-face rules expect them.
html_static_path = ["_static", "../assets/fonts/web"]
html_extra_path = ["starlight_colors.html"]  # Copy HTML reference to build output

# Intersphinx
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
}

# Pygments style for code highlighting
pygments_style = "monokai"  # code chrome is dark in BOTH themes (see the design)
pygments_dark_style = "monokai"


# -- Generated pages ---------------------------------------------------------
# The 21 cookbooks in examples/ hold 357 runnable recipes, and none of them
# appeared anywhere in this site. They are turned into pages here, on every build
# (including on Read the Docs), rather than being committed — a generated page
# that lives in git is a copy of the code that can drift from it, and the pages
# `literalinclude` the real functions precisely so that they cannot.
def _build_cookbook_pages(app):
    import subprocess
    import sys
    from pathlib import Path

    script = Path(__file__).parent.parent / "scripts" / "build_cookbook_pages.py"
    subprocess.run([sys.executable, str(script)], check=True)


def setup(app):
    app.connect("builder-inited", _build_cookbook_pages)
